### ISSUE TITLE
2019年7月言語アップデートの提案内容を更新

### ISSUE THREAD

**Issue by waddlaw** [haskell-jp/atcoder-haskell-resources#9]
言語アップデートの実施時期が大幅に遅れている影響により、以下のコマンドでインストールされる GHC のバージョンが当初期待していた `8.6.5` ではなく、`8.8.3` になってしまった。

```shell
$ curl https://get-ghcup.haskell.org -sSf | sh
```

~この結果、パッケージインストール時のバージョン制約が満たされなくなり、`massiv` などのパッケージが入らなくなってしまった。(具体的なコード例は以下のリンクを参照)~

以下のコードが `CE` になった理由は [massiv-0.4.2.0](https://hackage.haskell.org/package/massiv-0.4.2.0) → [massiv-0.5.1.0](https://hackage.haskell.org/package/massiv-0.5.1.0) になり、モジュール構造が変化したため。

- [AC するコード](https://atcoder.jp/contests/language-test-202001/submissions/9838835)
- [CE するコード](https://atcoder.jp/contests/language-test-202001/submissions/11418966)

実際に `massiv-0.5.1.0` に存在するモジュールを `import` したところ [AC](https://atcoder.jp/contests/language-test-202001/submissions/11429617) しました。

## 更新内容

- `ghcup` のインストール方法を [Manual install](https://gitlab.haskell.org/haskell/ghcup/blob/master/README.md#manual-install) に変更し、明示的に `ghc-8.8.3` をインストールする
- 提案ライブラリのバージョンを `ghc-8.8.3` に合わせて最新版に更新する
- 提案ライブラリの新規追加

**Comment by gksato** [comment]
~~`massiv` 自体は入っていて、major updateだったためにモジュールが削除されています~~ ああ、入らなくなったのでバージョンが上がったためにmajor updateになってしまった、って意味ですか。

**Comment by mizunashi-mana** [comment]
正規表現用のライブラリ `regex-tdfa` を追加してもらいたいです。

度々正規表現があるかないかでコーディング速度がかなり変わる問題が出るので。なお、テストでも「白昼夢」は正規表現があればほぼ自然な形 (これが想定解法なのかは分からないですが) でかけて、Ruby 回答にはそういうのがあるみたいですね:
https://atcoder.jp/contests/language-test-202001/submissions/10584624

正規表現があれば基本的には僕はいいですが、`regex-tdfa` を選択した理由を挙げておくと、

* それなりには速いこと (`libpcre` native 実装などには劣るものの、極端に遅いというわけではありません)
* `String` / `ByteString` / `Text` の全てにサポートがあること
* pure haskell 実装なので、インストールに手間取らないこと

です。

**Comment by gksato** [comment]
package additionは、AtCoder公式YouTube情報配信「あーだこーだー」第三回によるとdeployが4/11(土)のAtCoder Beginner Contest開始時刻時点では終わってる形なので、だいぶ厳しいとは思うんですが…。(普通に周知だと思って話してました、すみません)。

**Comment by mizunashi-mana** [comment]
この追加の話は、質問してみたんですが回答返ってこないんですよね
